### ISSUE TITLE
Cannot run nextjs example

### ISSUE THREAD

**Issue by Sleaf** [redbadger/crux#114]
https://github.com/redbadger/crux/blob/1887f773a4b0ef37f84c8dfda80468811c2083a3/examples/counter/web-nextjs/pages/index.tsx#L9

I clone this repo and run `cargo build` , and still cannot find this file after `pnpm install`, should I run something else?

**Comment by StuartHarris** [comment]
Hey, thanks for raising this. You will need to compile the `shared_types` library before you start (using `cargo build -p shared_types`). This will generate the foreign types for your shared library and package them so that they can be installed by pnpm.

If you were starting from scratch you would do the following:
```sh
git clone git@github.com:redbadger/crux.git
cd crux/examples/counter
cargo build -p shared_types
cd web-nextjs
pnpm install
pnpm dev
```

Let us know if you're still having problems.

**Comment by Sleaf** [comment]
@StuartHarris Oh, I found the generator configs in next.config.js
https://github.com/redbadger/crux/blob/1887f773a4b0ef37f84c8dfda80468811c2083a3/examples/counter/web-nextjs/next.config.js#L12

It generates `examples/counter/web-nextjs/shared/core` after `pnpm dev` , and the example works fine!

Thank you very much! I will take a deep look into this project.
